# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit, pre-push, commit-msg]
repos:
-   repo: https://github.com/SJSURoboticsTeam/hooks
    rev: v1.1.0
    hooks:
    -   id: word-blacklist-files
